FROM osrf/ros:iron-desktop

SHELL ["/bin/bash", "-c"]

WORKDIR /ssl_ws

RUN apt-get update &&\
    apt-get install -y python3-pip

COPY src src/

RUN for d in src/*/ ; do \
    if [ -f "$d/requirements.txt" ]; then \
        echo "Installing requirements for $d"; \
        pip install -r $d/requirements.txt; \
    fi; \
done

RUN source /opt/ros/iron/setup.bash && \
    colcon build

COPY ros_entrypoint.sh /
RUN chmod +x /ros_entrypoint.sh

ENTRYPOINT ["/ros_entrypoint.sh"]
CMD ["bash"]